### ISSUE TITLE
Grids / Dungeon Finder 

### ISSUE THREAD

**Issue by liviana1804** [teelolws/Altoholic-Retail#46] opened 2020-06-16 20:15 UTC
I am currently running Dragon Soul on several alts.  After I have run all the alt on a realm I go to Altoholic to verify I didn't miss any of them. However, that part of the grid is not registering anything.  It shows a big red X instead of the number 7/7 or 8/8 (don't remember how many bosses there are).
I am showing Altoholic V8.3.013.  I use twitch and update everyday from that application.  Let me know if you need any other information.  I am not good at reporting problems.

![Dungeon Finder](https://user-images.githubusercontent.com/15661355/84823576-cff72280-afdb-11ea-88f2-5fdd0c68de41.jpg)

**Comment by teelolws** [comment] 2020-06-16 20:30
Odd. Just ran it myself and its being tracked:
![image](https://user-images.githubusercontent.com/49792789/84824883-b524bc80-b074-11ea-92d5-9b5cd4677919.png)

I'll go and fully clear the place and see what happens.

**Comment by liviana1804** [comment] 2020-06-16 21:16
I just did a full reset of removing the wtf, interface and cache folders.  I then reinstalled Altoholic and Altoholic-Retail (Teelo's Fork).  I killed the first boss and it is still not registering. I am running Heroic 25 man.

**Comment by teelolws** [comment] 2020-06-16 21:18
I'm working on it now. The issue is that heroic and normal share a lockout, but its not tracking heroic properly.

**Comment by teelolws** [comment] 2020-06-16 21:28
Can you test this:

[altoholic - raid lockout fix.zip](https://github.com/teelolws/Altoholic-Retail/files/4789196/altoholic.-.raid.lockout.fix.zip)

**Comment by liviana1804** [comment] 2020-06-16 21:29
testing now.

**Comment by liviana1804** [comment] 2020-06-16 21:34
Yes!!  It works!  You are wonderful and I truly do appreciate your hard work on this addon that I have loved so well.

**Comment by teelolws** [comment] 2020-06-16 21:37
Great!

Fixed in: https://github.com/teelolws/Altoholic-Retail/compare/44925447b356...13a9b451a0f9

Will be uploaded to Curseforge at a future date. I still have other parts of the addon I'm working on.

**Closed by teelolws** 2020-06-16 21:37 UTC
