### ISSUE TITLE
Option icons do not appear in guild tab

### ISSUE THREAD

**Issue by comiluv** [teelolws/Altoholic-Retail#81] opened 2020-08-14 08:53 UTC
In Thaoky's altoholic, there's an icon which player can select to delete guild bank information, like screenshot below
![icons](https://user-images.githubusercontent.com/19642705/90231932-dcbaba00-de56-11ea-9179-1ce0bfd2043f.png)
But there aren't any in the forked version
![noicon](https://user-images.githubusercontent.com/19642705/90231974-ec3a0300-de56-11ea-816b-28884dc0b42d.png)
I noticed this recently as one of my alts quit a guild and the tooltip still showed item counts for a guild bank I no longer belong to

**Comment by teelolws** [comment] 2020-08-14 09:25
Thats because the character you're on isn't in a guild and/or hasn't seen your guilds bank yet. Its just a restriction of how that UI was designed.

**Comment by teelolws** [comment] 2020-08-14 09:42
Fixed in: https://github.com/teelolws/Altoholic-Retail/commit/80717f366ca5ab01846ecc2321a29fec32f70562

**Closed by teelolws** 2020-08-14 09:42 UTC
