### ISSUE TITLE
Echoes of Nyalotha tooltip display issue

### ISSUE THREAD

**Issue by Zasz333** [teelolws/Altoholic-Retail#15] opened 2020-03-27 11:04 UTC
The tooltip doesnt include echoes on other characters and the total sum says zero even for the active char with echoes.
The grid display does not say echoes but shows the available rchoes on each char.

As requested my saved variables.
[Altoholic settings.zip](https://github.com/teelolws/Altoholic-Retail/files/4392955/Altoholic.settings.zip)

**Comment by teelolws** [comment] 2020-03-27 11:51
Okay I've figured out the issue. And oh god this is going to be horrible to fix.

The problem is Thaoky coded it in a way that there is a limit of 63 currencies before it starts causing issues, including all the headers you see like "Battle for Azeroth", "Cataclysm" and such. Echoes of Ny'alotha is officially the 64th entry on the Currency tab now.

I'm going to have to completely redesign the way Currencies are stored, which means I also have to invalidate the currencies already stored. Once I make a fix for this and release it, you will have to re-log all your characters to get their currencies repopulated again.

This is going to take me a while to fix. I'll post updates here.

**Comment by Zasz333** [comment] 2020-03-27 15:27
I did as you asked and deleted my saved variabled, rescanned my characters and the issue is gone. Are you sure you need to redesign it anyway?

**Comment by teelolws** [comment] 2020-03-27 19:31
I will need to do the redesign, because all you've done is moved the bug to a different currency. If you log into all your characters, eventually you'll find a currency thats bugged like it. Whichever one ends up taking up slot 64. It will also happen when Blizzard adds more currencies to the game.

**Comment by teelolws** [comment] 2020-03-27 20:57
Fixed in latest commit. https://github.com/teelolws/Altoholic-Retail/commit/a8d1c71a63841afeefd7f9d174d82e92ebb05b91

**Closed by teelolws** 2020-03-27 20:57 UTC
